<?php
namespace Planeta\Autenticacao\Armazenamento;

/**
 * Test class for Sessao.
 * Generated by PHPUnit on 2012-04-25 at 14:27:29.
 */
class SessaoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Sessao
     */
    protected $sessao;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::__construct
     */
    protected function setUp() 
    {
        $this->sessao = new Sessao();
    }

    /**
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::estaVazio
     */
    public function testEstaVazio() 
    {
        $this->assertTrue($this->sessao->estaVazio());
    }

    /**
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::ler
     */
    public function testLerSemDados() {
        $this->assertNull($this->sessao->ler());
    }
    
    /**
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::ler
     */
    public function testLerComDados() 
     {
        $this->sessao->escrever(array('dados'));
        $this->assertTrue((bool) count($this->sessao->ler()));
    }

    /**
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::escrever
     */
    public function testEscrever() 
    {
        $dados = array('dados');
        $this->sessao->escrever($dados);
        
        $this->assertEquals($dados, $this->sessao->ler());
    }

    /**
     * @covers Planeta\Autenticacao\Armazenamento\Sessao::limpar
     */
    public function testLimpar() {
        $dados = array('dados');
        $this->sessao->escrever($dados);
        
        $this->sessao->limpar();
        
        
        $this->assertNull($this->sessao->ler());
    }
}