<?php
namespace Planeta\Mvc;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-22 at 17:35:08.
 */
class VisaoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Visao
     */
    protected $visao;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->visao = new Visao;
    }

    /**
     * @covers Planeta\Mvc\Visao::adicionarPasta
     */
    public function testAdicionarUmaPasta()
    {
        $pasta = PASTA_ACESSORIOS . '/Padrao/Visao/telas';
        $this->visao->adicionarPasta($pasta);
        
        $this->assertContains($pasta, $this->visao->pegarPastas());
        $this->assertEquals(1, count($this->visao->pegarPastas()));
    }
    
    /**
     * @covers Planeta\Mvc\Visao::adicionarPasta
     */
    public function testAdicionarDuasPastas()
    {
        $pasta = PASTA_ACESSORIOS . '/Padrao/Visao/telas';
        $this->visao->adicionarPasta($pasta);
        $this->assertContains($pasta, $this->visao->pegarPastas());
        
        $pasta = PASTA_ACESSORIOS . '/Padrao/Visao/';
        $this->visao->adicionarPasta($pasta);
        $this->assertContains($pasta, $this->visao->pegarPastas());
        
        $this->assertEquals(2, count($this->visao->pegarPastas()));
    }
    
    /**
     * @covers Planeta\Mvc\Visao::pegarPastas
     */
    public function testPegarPastasComNenhumaPastaAdicionada()
    {
        $this->assertEquals(array(), $this->visao->pegarPastas());
    }
    
    /**
     * @covers Planeta\Mvc\Visao::removerPasta
     */
    public function testRemoverPasta()
    {
        $pasta = PASTA_ACESSORIOS . '/Padrao/Visao/telas';
        $this->visao->adicionarPasta($pasta);
        $this->visao->removerPasta($pasta);
        
        $this->assertEquals(array(), $this->visao->pegarPastas());
    }

    /**
     * @covers Planeta\Mvc\Visao::renderizar
     */
    public function testRenderizarComDados()
    {
        $pasta = PASTA_ACESSORIOS . '/Padrao/Visao/telas';
        $this->visao->adicionarPasta($pasta);
        
        $this->visao->dados = array(array("nome" => "Nome", 
                                          "descricao" => "Descricao"));
        $conteudo = $this->visao->renderizar('inicial', 'inicial.php');
        
        $this->assertTrue((bool) $conteudo);
    }
    
    /**
     * @expectedException Planeta\Mvc\Excecao\VisaoNaoExiste
     */
    public function testRenderizarArquivoInexistente()
    {
        $this->visao->renderizar('inicial', 'naoExiste.php');
    }
}
