<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'padrao\\controlador\\inicial' => '/acessorios/Padrao/Controlador/Inicial.php',
                'padrao\\modelo\\usuario' => '/acessorios/Padrao/Modelo/Usuario.php',
                'planeta\\autenticacao\\armazenamento\\naopersistentetest' => '/Planeta/Autenticacao/Armazenamento/NaoPersistenteTest.php',
                'planeta\\autenticacao\\armazenamento\\sessaotest' => '/Planeta/Autenticacao/Armazenamento/SessaoTest.php',
                'planeta\\autenticacao\\autenticacaotest' => '/Planeta/Autenticacao/AutenticacaoTest.php',
                'planeta\\banco\\bancotest' => '/Planeta/Banco/BancoTest.php',
                'planeta\\banco\\tabelatest' => '/Planeta/Banco/TabelaTest.php',
                'planeta\\mvc\\controladortest' => '/Planeta/Mvc/ControladorTest.php',
                'planeta\\mvc\\mvctest' => '/Planeta/Mvc/MvcTest.php',
                'planeta\\mvc\\visaotest' => '/Planeta/Mvc/VisaoTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd